apiVersion: v1
kind: Pod
metadata: 
  name: kubia-manual-v3
  labels:
    creation_method: manual
    env: prod 
spec:
  containers:
    - name: hluksa/kubia
      image: kubia
      ports:
        - containerPort: 80